### ISSUE TITLE
Doesn't stop current track or re-activate it after combat

### ISSUE THREAD

**Issue by GhostwheelX** [veevelder/quick-combat#18]
It appears that if another track is currently playing when combat start, Quick Combat doesn't stop it, nor does it restart it after the combat ends. Is this a bug or an intended feature, and if it's intended, would it be possible to add is as an option?

**Comment by veevelder** [comment]
Is it multiple tracks thats not being stopped or just a single one? Also can you tell me what version of foundry you are using and version of Quick Combat? And if you can can you paste the output of the console when this happens. Thanks.

**Comment by GhostwheelX** [comment]
I'm having trouble re-creating the issue, I'll try to see if I can do so in my upcoming game and hopefully send you the console output.

Plutonium: 9.255
Quick Combat: 0.3.0

**Comment by GhostwheelX** [comment]
I'm having trouble re-creating the issue, I'll try to see if I can do so in my upcoming game and hopefully send you the console output.

Foundry: 9.255
Quick Combat: 0.3.0

**Comment by veevelder** [comment]
Thanks, and I vaguely remember coming across this issue once before, but I think I fixed it a few releases back. I will take a look as well as see if I cant recreate it.

**Comment by GhostwheelX** [comment]
It happens fairly often when I have multiple players connected and we're in the middle of a game, where I unfortunately can't take the time to get the console output, but I can confirm that it still happens, unfortunately.

**Comment by veevelder** [comment]
Sorry for taking so long to get on this, but I finally have time this weekend to work on it. Can I get some more information from you:

- What game system are you using?
- What other modules are you using and versions?
- How many players do you have?
- How many of those players are having issues (all/some/one)?
- how big are your playlists (number of items)?
- Are you using the Choose Playlist Option?
![Untitled](https://user-images.githubusercontent.com/5912400/162488649-e9355ffc-1fe0-4582-86ee-34ee4770a040.png)

Thanks for your help on this in advance

**Comment by veevelder** [comment]
closing since its been a while since last contact, if the issue still comes up just reopen it.
