### ISSUE TITLE
[FEATURE] please send intiative requests to players when asked for intiative

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [veevelder/quick-combat#27]
**Is your feature request related to a problem? Please describe.**
when i go for intiative its asking the gm to roll for the players.

**Describe the solution you'd like**
i would like only npcs and monsters to ask for initative when prompting and for players to receive their requests rather than the gm receiving all the requests to roll.

**Describe alternatives you've considered**

**Additional context**

**Comment by veevelder** [comment]
so it will ask the player to set their initiative if they are connected to the game, otherwise if the player is not connected it will prompt the GM

**Comment by ThingsCouldGetDicey** [comment]
> so it will ask the player to set their initiative if they are connected to the game, otherwise if the player is not connected it will prompt the GM

yeh that worked intodays session but it had this weird interaction where it wouldnt ask me as the gm what i wanted to roll as a prompt before i pressed begin combat. even tho i rolled intiative it asked me for the prompt after i clicked begin intiative. it also didnt give me the music menus. and played other music when i paused the music i manually set.

**Comment by veevelder** [comment]
looking back at your comment, what I think your issue and it has to do with how I got the mod to work. So when a token is added to the combat tracker (NPC and PC) it will ask for what type of initiative roll you want to use BEFORE combat has even started. This may or may not then roll for initiative (something ill have to test out) but depending on if you added the tokens manually (using the combat icon on the token) or by using the select all and hit the hot key method.

**Comment by veevelder** [comment]
ok, that should help me at least figure out whats going on

**Comment by veevelder** [comment]
the way the group NPC rolling option works is that I have to pop up that window when combat starts, not when adding NPCs to the combat tracker. This was to cut down on the amount of popups for the GM (if there are a lot of NPCs in the combat tracker)

Having said that I can do something similar to how the PCs work, where whenever you add a NPC to the combat tracker a window will pop up asking for initiative type, then roll it.

I did notice that if you add a NPC to the combat tacker, roll the initiative manually then click start combat it will ask you again, that should be fixed in the next update

**Comment by ThingsCouldGetDicey** [comment]
> the way the group NPC rolling option works is that I have to pop up that window when combat starts, not when adding NPCs to the combat tracker. This was to cut down on the amount of popups for the GM (if there are a lot of NPCs in the combat tracker)
> 
> Having said that I can do something similar to how the PCs work, where whenever you add a NPC to the combat tracker a window will pop up asking for initiative type, then roll it.
> 
> I did notice that if you add a NPC to the combat tacker, roll the initiative manually then click start combat it will ask you again, that should be fixed in the next update

im still having issue with the audio selection popping up for combat and it tries to do something funky to music if i put my own on and tell it to stop it tries to play another play list listed in the settings of the mod. then i have to stop that and then continue something manually.

**Comment by veevelder** [comment]
ok, so I tweeked how initiative is being prompted and it now will ask the player when their token is added to the combat tracker either from the right click menu or the hot key menu. This way their initiative should be set before combat is started regardless of the method
